static const char* YAXL_DEFAULT_SPRITE_2D_SHADER_VERT =
"#version 330\n"
"// 入力頂点座標\n"
"layout(location = 0) in vec4 in_Position;\n"
"\n"
"// 出力テクスチャ座標\n"
"out vec2 v_TexCoord;\n"
"\n"
"// スプライトの画像サイズ\n"
"uniform vec2 u_SpriteSize;\n"
"// スプライトの中心座標\n"
"uniform vec2 u_SpriteCenter;\n"
"// 拡大縮小\n"
"uniform vec2 u_SpriteScale;\n"
"// 回転角度\n"
"uniform float u_SpriteAngle;\n"
"// 平行移動量\n"
"uniform vec2 u_SpritePosition;\n"
"// 画像の切り出し位置\n"
"uniform vec2 u_TexturePosition;\n"
"// 画像の切り出しサイズ\n"
"uniform vec2 u_TextureSize;\n"
"// 画面サイズ\n"
"uniform vec2 u_ScreenSize;\n"
"\n"
"void main(void) {\n"
"    vec2 position = in_Position.xy;\n"
"    // スプライトの画像サイズ分拡大する\n"
"    position *= u_SpriteSize;\n"
"    // スプライトの中心座標の補正\n"
"    position -= u_SpriteCenter;\n"
"    // 拡大縮小\n"
"    position *= u_SpriteScale;\n"
"    // 回転\n"
"    vec2 rotate;\n"
"    rotate.x = position.x * cos(u_SpriteAngle) - position.y * sin(u_SpriteAngle);\n"
"    rotate.y = position.x * sin(u_SpriteAngle) + position.y * cos(u_SpriteAngle);\n"
"    position = rotate;\n"
"    // 平行移動\n"
"    position += u_SpritePosition;\n"
"    // 射影変換（画面の左上が原点、ｙ座標は下方向がプラスになっている座標を変換）\n"
"    position = position * vec2(2.0 / u_ScreenSize.x, -2.0 / u_ScreenSize.y) + vec2(-1.0, 1.0);\n"
"    // 頂点座標の出力\n"
"    gl_Position = vec4(position.x, position.y, 0.0, 1.0);\n"
"    // テクスチャ座標の出力（頂点座標とテクスチャ座標を兼用）\n"
"    v_TexCoord = in_Position.xy * u_TextureSize + u_TexturePosition;\n"
"}\n";

static const char* YAXL_DEFAULT_SPRITE_2D_SHADER_FRAG =
"#version 330\n"
"\n"
"// 入力テクスチャ座標\n"
"in vec2 v_TexCoord;\n"
"// 出力カラー\n"
"out vec4 out_FragColor;\n"
"\n"
"// スプライトカラー\n"
"uniform vec4 u_SpriteColor;\n"
"// テクスチャ\n"
"uniform sampler2D u_BaseMap;\n"
"\n"
"void main(void) {\n"
"	out_FragColor = texture(u_BaseMap, v_TexCoord) * u_SpriteColor;\n"
"}\n";
