static const char* YAXL_DEFAULT_3D_SPRITE_SHADER_VERT =
"#version 330\n"
"\n"
"// 入力頂点座標\n"
"layout(location = 0) in vec4 in_Position;\n"
"layout(location = 2) in vec2 in_TexCoord;\n"
"\n"
"// 出力テクスチャ座標\n"
"out vec2 v_TexCoord;\n"
"// スプライトの表示サイズ\n"
"uniform vec2 u_SpriteSize;\n"
"// スプライトの中心座標\n"
"uniform vec2 u_SpriteCenter;\n"
"// 拡大縮小\n"
"uniform vec2 u_SpriteScale;\n"
"// 回転角度\n"
"uniform float u_SpriteAngle;\n"
"// 平行移動量\n"
"uniform vec3 u_SpritePosition;\n"
"// 画像の切り出し位置\n"
"uniform vec2 u_TexturePosition;\n"
"// 画像の切り出しサイズ\n"
"uniform vec2 u_TextureSize;\n"
"// 視野変換行列\n"
"uniform mat4 u_matView;\n"
"// 透視変換行列\n"
"uniform mat4 u_matProjection;\n"
"\n"
"void main(void) {\n"
"	vec4 position = in_Position;\n"
"	// スプライトサイズ分拡大する\n"
"	position.xy *= u_SpriteSize;\n"
"	// スプライトの中心座標の補正\n"
"	position.xy -= u_SpriteCenter;\n"
"	// 拡大縮小\n"
"	position.xy *= u_SpriteScale;\n"
"	// 回転\n"
"	vec2 rotate;\n"
"	rotate.x = position.x * cos(u_SpriteAngle) - position.y * sin(u_SpriteAngle);\n"
"	rotate.y = position.x * sin(u_SpriteAngle) + position.y * cos(u_SpriteAngle);\n"
"	position.xy = rotate;\n"
"	// 視野変換の逆変換 (カメラとは逆の方向を向かせておく）\n"
"	position.xyz = position.xyz * mat3(u_matView);\n"
"	// 平行移動\n"
"	position.xyz += u_SpritePosition;\n"
"	// 視野変換\n"
"	vec4 view_position = u_matView * position;\n"
"	// 射影変換\n"
"	gl_Position = u_matProjection * view_position;\n"
"   // 反転\n"
"	vec2 tex_coord = vec2(in_TexCoord.x, 1.0 - in_TexCoord.y);\n"
"	// テクスチャ座標の出力\n"
"	v_TexCoord = tex_coord * u_TextureSize + u_TexturePosition;\n"
"}\n";

static const char* YAXL_DEFAULT_3D_SPRITE_SHADER_FRAG =
"#version 330\n"
"\n"
"// 入力テクスチャ座標\n"
"in vec2 v_TexCoord;\n"
"// 出力カラー\n"
"out vec4 out_FragColor;\n"
"\n"
"// スプライトカラー\n"
"uniform vec4 u_SpriteColor;\n"
"// テクスチャ\n"
"uniform sampler2D u_BaseMap;\n"
"\n"
"void main(void) {\n"
"	out_FragColor = texture(u_BaseMap, v_TexCoord) * u_SpriteColor;\n"
"}\n";
